### PR TITLE
New class called Utils to implement recurring functions like Sigmoid

### PR DESCRIPTION
**Pull request by Neorichi**

### CODE REVIEW

**Review by popigg — COMMENTED** [review]
I would change **Sigmoide** filename to "_Sigmoid_" to standardize names.

**Review by victorcpascua — COMMENTED** [review]
Falta el init

**Comment by victorcpascua** [comment]
> I would change **Sigmoide** filename to "_Sigmoid_" to standardize names.

**Comment by lumartin** [comment]
lets go

**Review by lumartin — APPROVED** [review]
I approve!

**Pull request merged**
